### PR TITLE
feat(Pass plan): mnemonic list item watcher

### PR DESCRIPTION
**Pull request by FMorrison87**
*Updated this is now straight from main* This PR hooks up state so that when you check 'add to watcher in the mnemonic pop-up in pass plan, the row gets an icon and 'watched' text.

### CODE REVIEW

**Review by Paterma — APPROVED** [review]
🎉

**Review by NicDominguez — CHANGES_REQUESTED** [review]
please merge in changes from PR #24 before merging this

**Review by NicDominguez — CHANGES_REQUESTED** [review]
When using the action menu in the Watcher list to remove the mnemonic from watcher the Mnemonic List Item watched icon/text does not update when the watched flag is set to false. 

Other than that bug you made some really excellent choices here and it's looking really good.

**Comment by FMorrison87** [comment]
> When using the action menu in the Watcher list to remove the mnemonic from watcher the Mnemonic List Item watched icon/text does not update when the watched flag is set to false.
> 
> Other than that bug you made some really excellent choices here and it's looking really good.

Great catch! That's fixed. @NicDominguez

**Review by NicDominguez — APPROVED** [review]

**Pull request merged**
